spring:
  datasource:
    url: jdbc:postgresql://db.poyvoucjpwlnmcwfyxvq.supabase.co:5432/postgres
    username: postgres
    password: EPICSVITBHOPAL@25

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: false # VERY IMPORTANT â€“ we disabled Flyway earlier

supabase:
  url: "https://poyvoucpjwlnmcwfyxvq.supabase.co"
  key: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBveXZvdWNqcHdsbm1jd2Z5eHZxIiwicm9zZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2Mjg3MDEzMiwiZXhwIjoyMDc4NDQ2MTMyfQ.znhMVARMWzU0r-7UXKiW7Iijsu9DbyDzP4VJuE1z2Wg"
